name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment: staging
    permissions: write-all
    outputs:
      commit_message: ${{ steps.get_message.outputs.commit_message }}
      pull_requests: ${{ steps.pr_info.outputs.pull_requests }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit message
        id: get_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%B)
          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: denniscual/pull-request-info@v1.1.0
        id: pr_info
        name: Get PR Info
        with:
          commit_sha: ${{ github.sha }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Build App
        env:
          COMMIT_MESSAGE: ${{ steps.get_message.outputs.commit_message }}
          PULL_REQUESTS: ${{ steps.pr_info.outputs.pull_requests }}
        run: pnpm build

      - name: Update Build Count Variable
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/FORCE_UPDATE_BUILD_COUNT \
            -d '{"name":"FORCE_UPDATE_BUILD_COUNT","value":"44"}'

      - name: Fetch Build Count Variable
        id: fetch_build_count
          run: |
            RESPONSE=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/FORCE_UPDATE_BUILD_COUNT)
            echo "Response from API: $RESPONSE"

  deploy_prod:
    needs: deploy_staging
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install

      - name: Build App
        env:
          COMMIT_MESSAGE: ${{ needs.deploy_staging.outputs.commit_message }}
          PULL_REQUESTS: ${{ needs.deploy_staging.outputs.pull_requests }}
        run: pnpm build

      - name: Log Repository Env Var
        run: echo "Repository environment variable ${{vars.FORCE_UPDATE_BUILD_COUNT}}"
