name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      force_update_build_count: ${{ steps.force-update.outputs.force_update_build_count }}
    steps:
      - uses: actions/checkout@v4

      - name: Force Update Build
        id: force-update
        uses: carepatron/force-update-build-action@v1.0.0
        with:
          commit_sha: ${{ github.sha }}
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          label: "force-update"
          force_update_build_count_name: "FORCE_UPDATE_BUILD_COUNT"

      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install
      - name: Build App
        env:
          FORCE_UPDATE_BUILD_COUNT: ${{ steps.force-update.outputs.force_update_build_count }}
        run: pnpm build

  deploy_prod:
    needs: deploy_staging
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install

      - name: Build App
        env:
          FORCE_UPDATE_BUILD_COUNT: ${{ needs.deploy_staging.outputs.force_update_build_count }}
        run: pnpm build
